feat: add link for typeform datenschutz and impressum
technologiestiftung/registration-assistant pull request #25
Opened 2024-02-08 14:11 UTC by aeschi

- typeform link only shows when german is selected

2024-02-12 09:27 UTC, raphael-arce requested changes
Got a couple of suggestions 👍  let me know what you think :)

2024-02-12 09:27 UTC, raphael-arce commented on src/App.tsx
> +      {language === availableLanguages[0] && (
I think we should rather use a named variable here, e.g. `availableLanguages['de-DE]`, to make it easier to understand which language is used, and also to make sure no type error occurs. I looked a bit into it and realized the current state of implementation won't allow it. I think we'd need to use [zod native enums](https://zod.dev/?id=native-enums) instead of [zod enums](https://zod.dev/?id=zod-enums) to type the `availableLanguages`. This is probably a bigger change than what is scoped in this ticket so maybe we can discuss and prioritize it first before implementing it.

2024-02-12 09:27 UTC, raphael-arce commented on src/App.tsx
> +      )}
I think it would make sense to move what is above in its own component, e. g. `<Feedback />`👍

2024-02-12 09:27 UTC, raphael-arce commented on src/App.tsx
>          </div>
Same here. Maybe let's move what is above in its own component (e.g. `<Footer />`) to keep the `App.tsx` short and easy to understand.

2024-02-12 13:16 UTC, raphael-arce commented
thanks 👍  lgtm!

2024-02-14 09:57 UTC, raphael-arce commented on src/components/feedback/index.tsx
> +            className="text-blue-500 underline"
@aeschi just noticed that this is not the same color than other links, the other links are `text-blue-700` to have enough contrast

2024-02-14 10:20 UTC, aeschi commented on src/components/feedback/index.tsx
> +            className="text-blue-500 underline"
Let's try to stick to one color with the most contrast and check again for the darker backgrounds. But technically a darker background would be better with a brighter text color.

2024-02-14 10:24 UTC, raphael-arce commented on src/components/feedback/index.tsx
> +            className="text-blue-500 underline"
Yes I agree 👍

2024-02-15 13:55 UTC, raphael-arce approved these changes
thx, lgtm 👍

2024-02-15 14:08 UTC, merged