fix: adjusted styling of language select across browsers
technologiestiftung/registration-assistant pull request #33
Opened 2024-02-19 11:04 UTC by raphael-arce

- adjusted styling of language select across browsers
- adjusted styling of home button
- added e2e test
- added some comments in the `index.css` to explain why these styles are there

2024-02-19 11:04 UTC, raphael-arce commented on src/index.css
@aeschi i'm not quite sure if the comments are well formulated and easy to understand. what do you think?

2024-02-20 08:49 UTC, aeschi requested changes
The language selector still looks a bit off (too wide) on safari and chrome on my phone.

<img  width="200px" src="https://github.com/technologiestiftung/registration-assistant/assets/56318362/e3ce7e0f-327e-4cbf-85a8-a594482b84ea">

2024-02-20 08:49 UTC, aeschi commented on src/index.css
@raphael-arce I think they are understandable 👍

2024-02-20 10:54 UTC, raphael-arce commented
Okay, will look into it! 👍

2024-02-20 12:40 UTC, raphael-arce commented
@aeschi after some research I think we cannot change styling of the box that gets opened on iOS, as it is defined by the operating system and there is apparently no way of changing that. This box unfortunately looks different in most browsers/OS: https://css-tricks.com/dropdown-default-styling/#aa-what-about-the-dropdown-itself

We could use a different element than the standard `<select>` and use some custom implementation to achieve a similar select/dropdown functionality, allowing full freedom of design. But I think for this situation it is better to stick to the standard. What do you think?

2024-02-20 13:16 UTC, aeschi commented
> @aeschi after some research I think we cannot change styling of the box that gets opened on iOS, as it is defined by the operating system and there is apparently no way of changing that. This box unfortunately looks different in most browsers/OS: https://css-tricks.com/dropdown-default-styling/#aa-what-about-the-dropdown-itself
> 
> We could use a different element than the standard `<select>` and use some custom implementation to achieve a similar select/dropdown functionality, allowing full freedom of design. But I think for this situation it is better to stick to the standard. What do you think?

ah interesting! Ok, then let's stickt with the standard.

2024-02-20 13:41 UTC, merged